In [1]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.linear_model import ridge_regression
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import Ridge

In [2]:
X = np.array([[1,1,2],[1,2,4],[1,3,6],[1,4,8]])
y = np.array([2,3,4,5])

### 4(a)

In [3]:
thetas = ridge_regression(X,y,1)
print("Thetas with Ridge Regression are\n",thetas)
print(X.dot(thetas))

Thetas with Ridge Regression are
 [0.44705882 0.23529412 0.47058824]
[1.62352941 2.8        3.97647059 5.15294118]


### 4(b)

In [4]:
def normalEquationRegression(X,y):
    X_t = np.transpose(X)
    temp = X_t.dot(X)
    try:
        print("Trying without regularisation")
        print(np.linalg.inv(X_t.dot(X)))
    except:
        print("Failure without regularisation")
    print("Now regularised")
    first = X_t.dot(X) + np.eye(temp.shape[0])
    first = np.linalg.inv(first)
    second = X_t.dot(y)
    return first.dot(second)

In [5]:
normalEquationRegression(X,y)

Trying without regularisation
Failure without regularisation
Now regularised


array([0.44705882, 0.23529412, 0.47058824])